x-api-common: &api-common
  build:
    context: .
    args:
      BUILDPLATFORM: linux/amd64
  image: api:v1
  volumes:
    - ./Configuration:/app/Configuration
  environment:
    ASPNETCORE_ENVIRONMENT: ''
  depends_on:
    - db
  deploy:
    resources:
      limits:
        cpus: '0.375'
        memory: '0.544GB'

networks:
  default:
    name: api_net
  tests:
    name: tests_net

services: # API - Instances
  api1:
    <<: *api-common
    hostname: api1
    ports:
      - "8080:8080"
  api2:
    <<: *api-common
    hostname: api2
    ports:
      - "8081:8080"
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro    
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - default
      - tests      
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.448GB'
  db: # Postgres tests
    build: SQLScripts/Postgres/.
    image: postgres:api
    environment:
      POSTGRES_DB: 'api'
      POSTGRES_PASSWORD: ${SA_PASSWORD}
    ports:
      - "5432:5432"    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2.560GB'
  # db: # SQL Server tests
  #   build: SQLScripts/Sqlserver/.
  #   image: sqlserver:api
  #   environment:
  #     ACCEPT_EULA: 'Y'
  #     MSSQL_SA_PASSWORD: ${SA_PASSWORD}
  #   ports:
  #     - "1433:1433"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: '4.0GB'